name: Syncing the repos
on:
  push:
    branches:
      - 'Jenkins'
  #  paths:  
  #   - 'sync/repo/Readme.md'
  workflow_dispatch:
jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install yq
        run: |
          wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod a+x /usr/local/bin/yq
          yq --version
      - name: clone repo
        run: |
          echo ${{ github.repository }}
          echo ${{ github.action_path }}
          cd ${{ github.action_repository }}
          ls
          echo ${{ secrets.ACTIONS_KEY }}
          git clone -b Jenkins https://Shankarsharm:${{ secrets.ACTIONS_KEY }}@github.com/Shankarsharm/FNV4_Comp1st.git
          ls
          pwd
          cd FNV4_Comp1st
          ls
      - name: Run Shell Script
        id: capture
        run: |
          cd ./.github/runfiles
          ls
          pwd
          chmod +x sync.sh
          ./sync.sh ${{ secrets.ACTIONS_KEY }} FNV4_SWC_Test
